# Documentation for branch policy: https://aka.ms/gim/docs/policy/branch-protection

name: main branch policy
description: restrict permissions to main branch
resource: repository
where:
configuration:
  branchProtectionRules:
    - branchNamePattern: "main"
      requiredApprovingReviewsCount: 1
      restrictsPushes: false
      allowsForcePushes: false
      allowsDeletions: false
