version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up: dep-bump"
      include: scope
  - package-ecosystem: pip
    directory: /rats/
    schedule:
      interval: weekly
    target-branch: main
    groups:
      package-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up: rats dep-bump"
      include: scope
  - package-ecosystem: pip
    directory: /rats-apps/
    schedule:
      interval: weekly
    target-branch: main
    groups:
      package-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up: rats-apps dep-bump"
      include: scope
  - package-ecosystem: pip
    directory: /rats-devtools/
    schedule:
      interval: weekly
    target-branch: main
    groups:
      package-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up: rats-devtools dep-bump"
      include: scope
