version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
  - package-ecosystem: "pip"
    token: ${{secrets.IMMUNOMICS}}
    directory: "/oneml-habitats/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "pip"
    token: ${{secrets.IMMUNOMICS}}
    directory: "/oneml-pipelines/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "pip"
    token: ${{secrets.IMMUNOMICS}}
    directory: "/oneml-processors/"
    schedule:
      interval: "daily"
    target-branch: "main"
