FROM mcr.microsoft.com/mirror/docker/library/ubuntu:24.04

# pipx is going to install things here for us
ENV PIPX_BIN_DIR="/usr/local/bin"
ENV PIPX_HOME=/opt/pipx
ENV PATH="${PIPX_BIN_DIR}:${PATH}"

RUN <<HEREDOC
set -eux

useradd -u 1001 -m nonroot

apt-get update

apt-get install -yqq --no-install-recommends \
    python3-minimal \
    python3-pip \
    pipx

pipx install poetry

apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/*
rm -rf /root/.cache
HEREDOC

COPY . /opt/rats
WORKDIR /opt/rats/rats-devtools
RUN <<HEREDOC
set -eux

pipx install .

rm -rf /root/.cache
HEREDOC

# nothing should be installed after this step
USER nonroot

CMD ["rats-devtools", "ci", "worker-node"]
