site_name: rats
repo_url: "https://github.com/microsoft/rats"
repo_name: "rats"
docs_dir: "docs"
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  features:
    # - navigation.tabs
    - navigation.sections
    # - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.follow
    - navigation.top
extra_css:
  - css/extra.css
# removed because of codeql detection
# https://github.com/microsoft/rats/security/code-scanning/3
# https://github.com/microsoft/rats/security/code-scanning/4
#extra_javascript:
#  - js/mathjax.js
#  - js/tex-mml-chtml.js
watch:
  - rats-apps/src
  - rats-devtools/src
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            # these paths should be relative from repo root
            - rats/src
            - rats-apps/src
            - rats-devtools/src
          options:
            show_if_no_docstring: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_signature_annotations: false
            group_by_category: true
            show_category_heading: false  # adds a lot of nesting in TOC navs
            show_root_heading: true  # adds nice grouping on pages showing more than one element
            signature_crossrefs: true
            merge_init_into_class: true
            annotations_path: source
            members_order: source
          inventories:
            - "https://docs.python.org/3/objects.inv"
            - "https://click.palletsprojects.com/en/stable/objects.inv"
            - "https://azuresdkdocs.z19.web.core.windows.net/python/azure-core/latest/objects.inv"
            - "https://azuresdkdocs.z19.web.core.windows.net/python/azure-identity/latest/objects.inv"
            - "https://azuresdkdocs.z19.web.core.windows.net/python/azure-ai-ml/latest/objects.inv"
  - awesome-pages
  - mkdocs-video:
      is_video: true
      video_controls: true
  - glightbox
markdown_extensions:
  # Allows for nicely styled notes and warnings: !!! note
  - admonition
  # Allows for adding attributes to markdown content: !(some-image){: align=left }
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # add paths relative to the devtools component here if you want to include them using -8<-
      # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      base_path:
        # always allow us to embed file paths from the root of the repo
        - !relative $config_dir
        # or relative from each src directory
        - !relative $config_dir/rats-apps/src
        - !relative $config_dir/rats-devtools/src
        # or test directory
        - !relative $config_dir/rats-apps/test
        - !relative $config_dir/rats-devtools/test
      # fail the mkdocs build if any snippets link to missing files
      # this delays painful bugs being found when disabled
      check_paths: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - def_list # definition / description lists
  - pymdownx.tasklist: # Allows us to make a Tasklist: [x] some checked thing
      custom_checkbox: true
  # removed because of codeql detection
  # https://github.com/microsoft/rats/security/code-scanning/3
  # https://github.com/microsoft/rats/security/code-scanning/4
  #  - pymdownx.arithmatex:
  #      generic: true
