FROM mcr.microsoft.com/mirror/docker/library/ubuntu:24.04

# pipx is going to install things here for us
ENV PIPX_BIN_DIR="/usr/local/bin"
ENV PIPX_HOME=/opt/pipx

RUN <<HEREDOC
# install dependencies
set -eux

useradd -u 1001 -m nonroot

apt-get update

apt-get install -yqq --no-install-recommends \
    python3-minimal \
    python3-pip \
    pipx

apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/*
rm -rf /root/.cache
HEREDOC

# copy the minimal number of files to install the devtools
# this way we can cache as many container layers as possible
COPY rats-contrib-jesus/pyproject.toml /opt/rats/rats-contrib-jesus/pyproject.toml
COPY rats-contrib-jesus/README.md /opt/rats/rats-contrib-jesus/README.md
# we have to account for the local dependencies and make sure they are also installable
# not sure i want to hand pick any files from local dependencies
COPY rats-apps /opt/rats/rats-apps
# create the skeleton of the packages so they install successfully
RUN <<HEREDOC
set -eux
mkdir -p /opt/rats/rats-contrib-jesus/src/python/rats/examples
touch /opt/rats/rats-contrib-jesus/src/python/rats/examples/__init__.py

HEREDOC

WORKDIR /opt/rats/rats-contrib-jesus

RUN <<HEREDOC
# install the package
set -eux

# create a clean python venv
python3 -m venv .venv
.venv/bin/pip install -e .

rm -rf /root/.cache
HEREDOC

COPY rats-contrib-jesus /opt/rats/rats-contrib-jesus

# nothing should be installed after this step
USER nonroot
