apiVersion: batch/v1
kind: Job
metadata:
  name: workflow
  namespace: workflows
spec:
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: Always
      restartPolicy: OnFailure
