from typing import NamedTuple


class Request(NamedTuple):
    name: str
    """The aml job name, often generated by the aml apis."""
    experiment_name: str
    """The aml experiment where the job was submitted, typically our component name."""
    studio_url: str
    """Link to the portal page for the submitted job."""

    wait: bool
    """Whether the application will wait for the completion of the aml job before returning."""
