from typing import NamedTuple


class Request(NamedTuple):
    job_name: str
    """The aml job name, often generated by the aml apis."""

    wait: bool
    """Whether the application will wait for the completion of the aml job before returning."""
