trigger: [main]
pr: [main]

pool:
  vmImage: ubuntu-latest
steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    showAlertLink: true
    failOnAlert: true
    logLevel: 'debug'
  env:
    EnableDetectorPoetry: true
