trigger: [main]
pr: [main]
schedules:
- cron: "0 0 * * 1"
  displayName: "Weekly: rats"
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest
variables:
  EnableDetectorPoetry: true
steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    showAlertLink: true
    failOnAlert: true
    logLevel: 'debug'
