trigger: [main]
pr: [main]

pool:
  vmImage: ubuntu-latest
env:
  EnableDetectorPoetry: true
steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    showAlertLink: true
    failOnAlert: true
    logLevel: 'debug'
