name: Build Docs
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
      publish-docs:
        description: 'whether to publish docs to the github pages'
        default: false
        required: true
        type: boolean
jobs:
  build-api-docs:
    runs-on: ["self-hosted", "1ES.Pool=oneml.github-runner-pool.dv5"]
    name: "build-api-docs"
    strategy:
      matrix:
        component:
          - rats-devtools
          - rats-apps
          - rats-pipelines
          - rats-processors
          - rats-examples-sklearn
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
        with:
          install-poetry: true
          install-devtools: true
      - name: something-simple
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          cd ${{ matrix.component }}
          rats-devtools ci install
          rats-devtools ci build-wheel
      - name: "upload-artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "api-docs.${{ matrix.component }}"
          path: "${{ matrix.component }}/docs/api/"
  generate-docs:
    runs-on: ["self-hosted", "1ES.Pool=oneml.github-runner-pool.dv5"]
    needs: [ "build-api-docs" ]
    name: "generate-docs"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
        with:
          install-poetry: true
          install-devtools: true
      - name: download-rats-devtools
        uses: actions/download-artifact@v4
        with:
          path: rats-devtools/docs/api/
          pattern: "api-docs.rats-devtools"
          merge-multiple: false
      - name: download-rats-apps
        uses: actions/download-artifact@v4
        with:
          path: rats-apps/docs/api/
          pattern: "api-docs.rats-apps"
          merge-multiple: false
      - name: mkdocs-build
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          cd rats-devtools
          # disabled for now
          # rats-devtools ci update-version "$PACKAGE_VERSION"
          rats-devtools ci install
          rats-devtools ci mkdocs-build
      - name: "upload-gh-pages"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "rats-devtools/dist/site"
#  deploy-docs:
#    # temporarily slowing down builds to make sure we avoid deploying docs from a failed build
#    needs: ["generate-docs"]
#    # this one can run anywhere
#    runs-on: "ubuntu-latest"
#    name: "deploy-docs"
#    steps:
#      # let us reach things installed by pipx
#      - name: "deploy-gh-pages"
#        if: "${{ inputs.publish-docs }}"
#        id: deployment
#        uses: actions/deploy-pages@v4
