name: Build Docs
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
jobs:
  generate-docs:
    runs-on: ["self-hosted", "1ES.Pool=oneml.github-runner-pool.dv5"]
    name: "generate-docs"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
        with:
          install-poetry: true
          install-devtools: true
          devtools-component: "rats-devtools"
      - name: mkdocs-build
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          cd rats-devtools
          rats-devtools.pipx ci update-version "$PACKAGE_VERSION"
          rats-devtools.pipx ci install
          rats-devtools.pipx docs mkdocs-build
      - name: "upload-gh-pages"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "rats-devtools/dist/site"
