name: Build Docs
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
jobs:
  generate-docs:
    runs-on: "ubuntu-24.04"
    name: "generate-docs"
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
        with:
          install-uv: true
          install-devtools: true
      - name: mkdocs-build
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          cd rats-devtools
          uv version "$PACKAGE_VERSION"
          rats-ci install
          rats-docs build
      - name: "upload-gh-pages"
        uses: actions/upload-pages-artifact@v4
        with:
          path: "rats-devtools/dist/site"
