name: Build Docs
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
      publish-docs:
        description: 'whether to deploy the generated docs to github pages'
        required: false
        default: false
        type: boolean
permissions:
  contents: read
jobs:
  generate-docs:
    runs-on: "ubuntu-24.04"
    name: "generate-docs"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - uses: ./.github/actions/setup-environment
        id: runner-context
        with:
          install-uv: true
          install-devtools: true
      - name: mkdocs-build
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          cd rats-devtools
          uv version "$PACKAGE_VERSION"
          rats-ci install
          rats-docs build
      - name: "upload-gh-pages"
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: "rats-devtools/dist/site"
  deploy-docs:
    name: "deploy-docs"
    if: "${{ inputs.publish-docs }}"
    needs: generate-docs
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      pages: write
      id-token: write
    steps:
      - name: "deploy-gh-pages"
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
