name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ["self-hosted", "1ES.Pool=oneml-test-300"]

    steps:
    - uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
          echo installing azurecli
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          echo done
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag immunodata.azurecr.io/oneml-test:$(date +%s)
