name: Main
on:
  push:
    branches: [ "main" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  pages: write
  id-token: write
  attestations: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    permissions:
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      sha: ${{ github.sha }}
  build-wheels:
    uses: ./.github/workflows/build-wheels.yaml
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      sha: ${{ github.sha }}
  build-docs:
    uses: ./.github/workflows/build-docs.yaml
    permissions:
      contents: read
    with:
      sha: ${{ github.sha }}
  release:
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: write
      pages: write
      id-token: write
    needs:
      - build-docs
      - build-wheels
      - checks
    with:
      sha: ${{ github.sha }}
      publish-docs: true
      publish-wheels: true
