name: Main
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    permissions:
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      sha: ${{ github.sha }}
  build-docs:
    uses: ./.github/workflows/build-docs.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      sha: ${{ github.sha }}
      publish-docs: true
