name: PR
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  id-token: write
  attestations: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    permissions:
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      sha: ${{ github.sha }}
  build-wheels:
    uses: ./.github/workflows/build-wheels.yaml
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      sha: ${{ github.sha }}
  build-docs:
    uses: ./.github/workflows/build-docs.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      sha: ${{ github.sha }}
