name: PR
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    permissions:
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      sha: ${{ github.sha }}
  build-wheels:
    uses: ./.github/workflows/build-wheels.yaml
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      sha: ${{ github.sha }}
  build-docs:
    uses: ./.github/workflows/build-docs.yaml
    permissions:
      contents: read
    with:
      sha: ${{ github.sha }}
  codeql:
    uses: ./.github/workflows/codeql.yaml
    permissions:
      security-events: write
      actions: read
      contents: read
    with:
      sha: ${{ github.sha }}
  release:
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: read
    needs:
      - build-docs
      - build-wheels
      - checks
      - codeql
    with:
      sha: ${{ github.sha }}
      publish-docs: false
      publish-wheels: false
