name: Release
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
      publish-docs:
        description: 'whether to publish docs to the github pages'
        required: true
        type: boolean
      publish-wheels:
        description: 'whether to publish wheels to the configured feed'
        required: true
        type: boolean
jobs:
  publish-wheels:
    name: "publish-wheels"
    runs-on: "ubuntu-latest"
    if: "${{ inputs.publish-wheels }}"
    strategy:
      fail-fast: false
      matrix:
        component:
          - rats-apps
          - rats-devtools
    environment:
      name: pypi
      url: https://pypi.org/p/${{ matrix.component }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: download-wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "wheels.${{ matrix.component }}"
          path: dist/
      - name: Upload assets to GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        run: gh release upload "$TAG_NAME" dist/* --clobber
      - name: publish-wheels
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1

  publish-docs:
    name: "deploy-docs"
    runs-on: "ubuntu-latest"
    if: "${{ inputs.publish-docs }}"
    timeout-minutes: 10
    permissions:
      pages: write
      id-token: write
    steps:
      - name: "deploy-gh-pages"
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
