name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ["self-hosted", "1ES.Pool=oneml-test-300"]

    steps:
    - uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
          az login \
            --identity \
            -u /subscriptions/7bd3802d-452e-4b2a-964e-e2c996bc7477/resourcegroups/immunodata.aks/providers/microsoft.managedidentity/userassignedidentities/k8s-pods-tekton-pipeline

          az acr login --name immunodata
          az acr show -n oneml -g oneml-github-test
          bin/docker-build oneml-pipelines

          docker run immunodata.azurecr.io/oneml/oneml-pipelines:latest flake8
          docker run immunodata.azurecr.io/oneml/oneml-pipelines:latest mypy
          docker run immunodata.azurecr.io/oneml/oneml-pipelines:latest pytest
